"""
local_tests/test_quality_filters.py
Unit tests for src/curation/quality_filters.py.

Usage:
    pytest local_tests/test_quality_filters.py -v
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.curation.quality_filters import (
    evaluate_quality,
    is_ast_parseable,
    is_within_size_bounds,
    looks_binary,
    looks_minified_or_generated,
    scan_for_secrets,
)

SECRET_PATTERNS = [
    r"(?i)aws_secret_access_key\s*=\s*['\"]?[A-Za-z0-9/+=]{20,}",
    r"ghp_[A-Za-z0-9]{36}",
    r"(?i)password\s*=\s*['\"]?\S{8,}",
]


class TestIsAstParseable:
    def test_valid_source(self):
        assert is_ast_parseable("x = 1 + 2") is True

    def test_invalid_syntax(self):
        assert is_ast_parseable("def foo(:\n    pass") is False


class TestIsWithinSizeBounds:
    def test_within_bounds(self):
        assert is_within_size_bounds(1000, 135, 13457) is True

    def test_too_small(self):
        assert is_within_size_bounds(50, 135, 13457) is False

    def test_too_large(self):
        assert is_within_size_bounds(20000, 135, 13457) is False

    def test_boundary_values_inclusive(self):
        assert is_within_size_bounds(135, 135, 13457) is True
        assert is_within_size_bounds(13457, 135, 13457) is True


class TestLooksBinary:
    def test_text_content(self):
        assert looks_binary("def foo():\n    pass\n") is False

    def test_null_byte_present(self):
        assert looks_binary("some\x00binary\x00content") is True


class TestLooksMinifiedOrGenerated:
    def test_normal_code_passes(self):
        content = "def foo(x):\n    return x + 1\n\ndef bar(y):\n    return y - 1\n"
        assert looks_minified_or_generated(content, 1000, 300, ["@generated"]) is False

    def test_generated_marker_detected(self):
        content = "# @generated by some tool\nx = 1\n"
        assert looks_minified_or_generated(content, 1000, 300, ["@generated"]) is True

    def test_generated_marker_case_insensitive(self):
        content = "# This file was GENERATED automatically\nx = 1\n"
        assert (
            looks_minified_or_generated(content, 1000, 300, ["this file was generated"])
            is True
        )

    def test_minified_single_long_line_flagged(self):
        long_line = "x = 1; " * 300  # long AND high average line length (single line)
        assert looks_minified_or_generated(long_line, 200, 100, []) is True

    def test_long_string_literal_not_flagged_as_minified(self):
        """One long line in an otherwise normal file shouldn't trip the
        minified heuristic — average line length stays low."""
        content = "x = 1\n" + ("y = '" + "a" * 2000 + "'\n") + "z = 2\n" * 20
        assert looks_minified_or_generated(content, 500, 300, []) is False

    def test_empty_content(self):
        assert looks_minified_or_generated("", 1000, 300, []) is False


class TestScanForSecrets:
    def test_no_secret_present(self):
        assert scan_for_secrets("x = 1\ny = 2\n", SECRET_PATTERNS) is False

    def test_password_pattern_detected(self):
        assert scan_for_secrets('password = "supersecret123"', SECRET_PATTERNS) is True

    def test_github_token_detected(self):
        content = "token = 'ghp_" + "a" * 36 + "'"
        assert scan_for_secrets(content, SECRET_PATTERNS) is True

    def test_aws_key_detected(self):
        content = "aws_secret_access_key = 'AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHH'"
        assert scan_for_secrets(content, SECRET_PATTERNS) is True


class TestEvaluateQuality:
    def _eval(self, content: str, size_bytes: int | None = None):
        return evaluate_quality(
            content=content,
            size_bytes=size_bytes if size_bytes is not None else len(content.encode("utf-8")),
            size_min=135,
            size_max=13457,
            max_line_length=1000,
            min_avg_line_length_for_minified_check=300,
            generated_markers=["@generated"],
        )

    def test_good_file_kept(self):
        content = "def foo(x):\n    return x + 1\n" * 10  # comfortably within size bounds
        result = self._eval(content)
        assert result.keep is True
        assert result.reason == "ok"

    def test_too_small_rejected(self):
        result = self._eval("x = 1")
        assert result.keep is False
        assert result.reason == "size_out_of_bounds"

    def test_ast_invalid_rejected(self):
        content = "def foo(:\n    pass\n" * 20  # padded to pass size bounds, still invalid
        result = self._eval(content)
        assert result.keep is False
        assert result.reason == "ast_invalid"

    def test_binary_rejected(self):
        content = "x = 1\x00\n" * 50
        result = self._eval(content)
        assert result.keep is False
        assert result.reason == "binary"
